// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCxhrc_5z594QCo7_isFBMQelmYPX_bDM',
    appId: '1:808061890860:web:95c9ffc2886d6cb34f7c89',
    messagingSenderId: '808061890860',
    projectId: 'flutterfirenotes-ad653',
    authDomain: 'flutterfirenotes-ad653.firebaseapp.com',
    storageBucket: 'flutterfirenotes-ad653.appspot.com',
    measurementId: 'G-GYT3JS2MXG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1HEMIk-mCACq1yVztYWzbIMo6As4iJDQ',
    appId: '1:808061890860:android:8d8420c68f99a91e4f7c89',
    messagingSenderId: '808061890860',
    projectId: 'flutterfirenotes-ad653',
    storageBucket: 'flutterfirenotes-ad653.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpgsIBn3S68NfwPpYQ8K-ekbY2o-VtWGg',
    appId: '1:808061890860:ios:e7fa89ab0f5bfbba4f7c89',
    messagingSenderId: '808061890860',
    projectId: 'flutterfirenotes-ad653',
    storageBucket: 'flutterfirenotes-ad653.appspot.com',
    iosClientId: '808061890860-3ea7pejmmroiru6jutb4pslc0i0i4397.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpgsIBn3S68NfwPpYQ8K-ekbY2o-VtWGg',
    appId: '1:808061890860:ios:e7fa89ab0f5bfbba4f7c89',
    messagingSenderId: '808061890860',
    projectId: 'flutterfirenotes-ad653',
    storageBucket: 'flutterfirenotes-ad653.appspot.com',
    iosClientId: '808061890860-3ea7pejmmroiru6jutb4pslc0i0i4397.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterNotes',
  );
}
